apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabob-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metabob-springboot
  template:
    metadata:
      labels:
        app: metabob-springboot
    spec:
      containers:
        - name: springboot
          image: rohittera7/metabob-docker-demo:metabobdocker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: metabo-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: metabob-springboot
